version: '3.7'

services:
  mongo:
    image: mongo
  server:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
