name: Build and Test

# Run on push or PRs for master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install packages
      run: yarn install

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0

    - name: Build and Run Tests
      run: yarn test
